#!/bin/bash

#for i in {1..25}; do
#    if [[ -d "f$i" ]]; then
#        gcc -o $i f$i/*.c -lm
#    fi
#done

for i in {1..25}; do
    if [[ -f $i ]]; then
        let f=i+1
        if [[ -f $f ]]; then
            continue
        else
            gcc -o $i f$i/*.c -lm && ./$i
        fi
    fi
done