#!/bin/bash

for i in {1..25}; do
    if [[ -d code/$i ]]; then
        let f=i+1
        if [[ -d code/$f ]]; then
            continue
        else
            gcc -o bin/$i code/$i/*.c -Wall -Werror -lm && ./bin/$i
        fi
    fi
done