#!/bin/bash

for i in {1..25}; do
    if [[ -d "code/$i" ]]; then
        continue
    fi
    mkdir "code/$i"
    cp template.c code/$i/main.c
    cp template.h code/$i/main.h
    touch "code/$i/in.txt"
    break
done